### ISSUE TITLE
Unknown Class – yii\base\UnknownClassException

### ISSUE THREAD

**Issue by vinayaWD** [annaselh/yii2adminlte#1]
Hello,

I have installed "yii2 advanced" latest vesrion and put this extension to my yii folder as described but the url "http://localhost/yii/backend/web/index.php?r=site/login" return exception "Unknown Class – yii\base\UnknownClassException".

Please reply.

**Comment by pahday** [comment]
Please go through instructions for installation in README.md and check once again.. i tried and it worked perfectly...

**Comment by annaselh** [comment]
@vinayaWD Have you change the namespace in AdminLteAsset.php and FontawesomeAsset.php files? If you use advanced version change the namespace 
```namespace app\assets;```
to 
```namespace backend\assets;```

And in AdminLteAsset depends change ```'app\assets\FontawesomeAsset'``` to ```'backend\assets\FontawesomeAsset'```

**Comment by annaselh** [comment]
@vinayaWD I notice what the problem is. I forgot to write this in the instructions.

in view/layouts/login.php don't forget to change.
```use app\assets\AdminLteAsset``` to ```use backend\assets\AdminLteAsset```
and 
```use app\assets\AppAsset``` to ```use backend\assets\AppAsset```

**Comment by vinayaWD** [comment]
Hello, 

Thanks for reply, I have already made this changes in backend\views\layouts\login.php, and now it is working.
